In [1]:
#THIS CODE ONLY DO THE WHOLE DATA TRAINING, NO CROSS_VALIDATION AND FEATURE SELECTION
import pandas as pd
import numpy as np
import newSom
import dataset_read
import researchpy as rp
import scipy.stats as stats
import matplotlib.pyplot as plt
import warnings
import experiment
warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning) 

In [3]:
dataread = dataset_read.DATAREAD()
csv = pd.read_csv("Iris.csv")
csv = csv.drop(columns=['Id'])
dataread.stringToIntIrisDataSet(csv,"Species")
csv_test = csv.sample(int(csv.shape[0]*0.3))
csv_training = csv.drop(csv_test.index,axis = 0)
dataread.initializedataset(csv,csv_training,csv_test,"Species",10)

In [15]:
def de_correlate_df(df):
    X_aux = df.copy()
    for col in df.columns:
        X_aux[col] = df[col].sample(len(df)).values
        print(df[col].sample(len(df)).values)
        
    return X_aux

In [16]:
print(csv)
de_correlate_df(csv)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0              5.1           3.5            1.4           0.2       0
1              4.9           3.0            1.4           0.2       0
2              4.7           3.2            1.3           0.2       0
3              4.6           3.1            1.5           0.2       0
4              5.0           3.6            1.4           0.2       0
..             ...           ...            ...           ...     ...
145            6.7           3.0            5.2           2.3       2
146            6.3           2.5            5.0           1.9       2
147            6.5           3.0            5.2           2.0       2
148            6.2           3.4            5.4           2.3       2
149            5.9           3.0            5.1           1.8       2

[150 rows x 5 columns]
[4.4 4.9 6.3 6.4 6.3 6.8 4.8 5.1 6.8 7.7 6.7 7.7 5.9 5.5 6.1 6.7 6.7 5.5
 6.4 5.7 5.8 6.9 5.3 7.  6.4 7.6 6.5 4.4 5.8 5.8 5.6 6.6 7.7 6.

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0              7.7           2.7            1.6           1.8       2
1              4.4           3.6            4.5           2.0       1
2              6.4           3.5            1.4           0.4       1
3              7.1           2.4            3.9           1.3       2
4              6.1           3.5            5.3           0.2       2
..             ...           ...            ...           ...     ...
145            6.0           2.9            1.1           1.8       1
146            5.4           3.2            6.1           1.9       0
147            6.0           2.5            4.7           1.1       2
148            5.0           2.5            3.3           0.5       2
149            5.1           2.2            5.6           0.1       0

[150 rows x 5 columns]

In [8]:
from sklearn.metrics.cluster import normalized_mutual_info_score

normalized_mutual_info_score([0,2,2,2,1,0,2,0,1,2,2,2,2,0,1,2,1,2,2,2,2,2,1,0,0,1,1,2,0,1,0,2,0,2,0,1,2
,2,0,0,0,1,0,1,1],[0,1,1,1,1,0,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,1,0,1,0,1,0,1,1
,1,0,0,0,1,0,1,1])



0.7294992723113822

In [9]:
normalized_mutual_info_score([0,2,2,2,1,0,2,0,1,2,2,2,2,0,1,2,1,2,2,2,2,2,1,0,0,1,1,2,0,1,0,2,0,2,0,1,2
,2,0,0,0,1,0,1,1],[0,1,1,1,1,0,1,0,1,1,1,1,1,0,1,0,1,1,1,1,0,0,1,0,0,1,1,0,0,1,0,1,0,1,0,0,0
,1,0,0,0,1,0,1,1])

0.41560389572417983

In [60]:
import numpy as np
m= 4
n= 3
A = np.random.rand(m, n)
print(A)

[[0.50696865 0.52009202 0.98425229]
 [0.40735692 0.52713513 0.99199859]
 [0.91630435 0.27788025 0.50607411]
 [0.19314552 0.49604701 0.18290032]]


In [67]:
U, S, VT = np.linalg.svd(A,full_matrices=False)

print(VT)
U = U[:3, :]
S = S[:3]

print(f" u{U}, np.diagS {np.diag(S)} VT{VT}")
A_compressed = U.dot(np.diag(S)).dot(VT)
print(A_compressed)

[[-0.51865707 -0.43696987 -0.73488242]
 [-0.85471029  0.28667661  0.4327665 ]
 [-0.02156768 -0.85256897  0.5221695 ]]
 u[[-0.60791188  0.25377772  0.17414291]
 [-0.58642407  0.41583395  0.1746938 ]
 [-0.48520953 -0.86748303  0.02215376]], np.diagS [[1.99620564 0.         0.        ]
 [0.         0.5585136  0.        ]
 [0.         0.         0.34223653]] VT[[-0.51865707 -0.43696987 -0.73488242]
 [-0.85471029  0.28667661  0.4327665 ]
 [-0.02156768 -0.85256897  0.5221695 ]]
[[0.50696865 0.52009202 0.98425229]
 [0.40735692 0.52713513 0.99199859]
 [0.91630435 0.27788025 0.50607411]]


In [66]:
U, S, VT = np.linalg.svd(A,full_matrices=False)
print(VT)
U = U[:, :2]

VT = VT[: ,:2]

S = S[:2]
print(f" u{U}, np.diagS {np.diag(S)} VT{VT}")
A_compressed = U.dot(np.diag(S)).dot(VT)
print(A_compressed)

[[-0.51865707 -0.43696987 -0.73488242]
 [-0.85471029  0.28667661  0.4327665 ]
 [-0.02156768 -0.85256897  0.5221695 ]]
 u[[-0.60791188  0.25377772]
 [-0.58642407  0.41583395]
 [-0.48520953 -0.86748303]
 [-0.22610101  0.10075806]], np.diagS [[1.99620564 0.        ]
 [0.         0.5585136 ]] VT[[-0.51865707 -0.43696987]
 [-0.85471029  0.28667661]
 [-0.02156768 -0.85256897]]


ValueError: shapes (4,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [69]:
import numpy as np

# Define the original matrix A
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the SVD of A
U, s, Vt = np.linalg.svd(A)

# Define the number of columns to retain in the compressed matrix
k = 2

# Truncate the matrices U and s to retain only the desired number of columns
U_trunc = U[:, :k]
s_trunc = np.diag(s[:k])

# Compute the compressed matrix A'
A_prime = U_trunc.dot(s_trunc).dot(Vt)

print("Original matrix A:\n", A)
print("Compressed matrix A':\n", A_prime)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [8]:
print(Bi)

[[0.51841144 0.69933576 0.94494415]
 [0.54889674 0.63565491 0.73274428]
 [0.72307114 0.64697425 0.47884206]
 [0.50905211 0.43023488 0.27261564]]


In [31]:
# specify the number of singular values to keep for each row
k = 2
# compute the compressed matrix B
B = np.zeros((m, k))
for i in range(m):
    print(k)
    # extract the ith row of Vt, which corresponds to the ith row of A
    Vti = VT[:k-1, :]
    print(Vti)
    # compute the compressed representation of the ith row
    Bi = U[i, :k].dot(np.diag(S[:k])).dot(Vti)
    # store the compressed representation in the ith row of B
    B[i, :] = Bi
    
print(Bi)

2
[[-0.46173097 -0.66818616 -0.58337961]]


ValueError: shapes (2,) and (1,3) not aligned: 2 (dim 0) != 1 (dim 0)

In [7]:
import numpy as np
from sklearn.decomposition import TruncatedSVD


data = np.random.rand(3, 4)
print(data)
svd = TruncatedSVD(n_components=4, n_iter=7, random_state=42,algorithm='randomized')
svd.fit(data)
data_compressed = svd.transform(data)  

print(data_compressed)
data_reconstructed = svd.inverse_transform(data_compressed)
print(data_reconstructed)

[[0.0353211  0.35868446 0.04429971 0.19551601]
 [0.1618992  0.7487516  0.98127903 0.39200188]
 [0.55929402 0.01299394 0.32391638 0.58015278]]
[[ 0.30711083 -0.07401578  0.26513335]
 [ 1.27362243 -0.27757349 -0.06521632]
 [ 0.63593928  0.59165221  0.002572  ]]
[[0.0353211  0.35868446 0.04429971 0.19551601]
 [0.1618992  0.7487516  0.98127903 0.39200188]
 [0.55929402 0.01299394 0.32391638 0.58015278]]


In [3]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

data = np.random.rand(4, 3)
print(f"data{data}")
data_transposed = data.T 
print(f" data_transposed {data_transposed}")
svd = TruncatedSVD(n_components=4, n_iter=7, random_state=42)

svd.fit(data_transposed)
data_compressed_transposed = svd.transform(data_transposed)
print(f" data_compressed_transposed {data_compressed_transposed}")
data_reconstructed = svd.inverse_transform(data_compressed_transposed)
print(f" data_reconstructed {data_reconstructed}")
data_reconstructedT = data_reconstructed.T 
print(f" data_compressed {data_reconstructedT}")


data[[0.12423118 0.20248949 0.45945129]
 [0.5871361  0.68925684 0.17533542]
 [0.59463147 0.60559635 0.95107681]
 [0.90711631 0.85289638 0.14618814]]
 data_transposed [[0.12423118 0.5871361  0.59463147 0.90711631]
 [0.20248949 0.68925684 0.60559635 0.85289638]
 [0.45945129 0.17533542 0.95107681 0.14618814]]
 data_compressed_transposed [[ 1.21235883 -0.25024695 -0.06458564]
 [ 1.24937881 -0.21231592  0.06504382]
 [ 0.84635395  0.67188451 -0.00350138]]
 data_reconstructed [[0.12423118 0.5871361  0.59463147 0.90711631]
 [0.20248949 0.68925684 0.60559635 0.85289638]
 [0.45945129 0.17533542 0.95107681 0.14618814]]
 data_compressed [[0.12423118 0.20248949 0.45945129]
 [0.5871361  0.68925684 0.17533542]
 [0.59463147 0.60559635 0.95107681]
 [0.90711631 0.85289638 0.14618814]]
